NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

_app_todo:
    resource: "@NzTodoBundle/Controller/AppController.php"
    type:     annotation
    prefix:   /web

_api_todo:
    resource: "@NzTodoBundle/Controller/TodoController.php"
    type:     rest
