<?php

namespace Nz\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository
{

    public function findAllOrderedById()
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT t FROM NzTodoBundle:Todo t ORDER BY t.id DESC'
                )
                ->getResult();
    }

    public function fetch($start, $limit, $pager = false)
    {

        return $this->getEntityManager()
                ->createQuery(
                    'SELECT t FROM NzTodoBundle:Todo t ORDER BY t.id DESC'
                )
                ->setFirstResult($start)
                ->setMaxResults($limit)
                ->getResult();
    }

    public function persistAndFlush($entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function removeAndFlush($entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
